name: Visual Studio Extension for Emscripten

on:
  [ push, pull_request ]

jobs:

  build:
    strategy:
        matrix:
          config:
            - name: vs2017
              runs-on: windows-2016
              config-name: Release VS2017
              vsix-source: source.extension.vs2017.vsixmanifest
              msbuild-path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\bin"
            - name: vs2022
              runs-on: windows-2022
              config-name: Release
              vsix-source: source.extension.vsixmanifest
              msbuild-path: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\bin"

    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ${{ matrix.config.runs-on }}

    env:
      Solution_Name: Emscripten.sln
      MSBuild_Path: ${{ matrix.config.msbuild-path }}


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copy Vsix Source
      working-directory: Emscripten.Build.Definition
      run: |
        cp ${{ matrix.config.vsix-source }} source.extension.vsixmanifest

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Cache Nuget packages 
      uses: actions/cache@v1
      id: cache
      with:
        path: ./packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

    - name: Restore Nuget package
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: nuget restore $env:Solution_Name
      
    - name: Build the application
      run: |
        Set-Item Env:Path "$env:MSBuild_Path;$env:Path"
        msbuild $env:Solution_Name /p:Configuration="${{ matrix.config.config-name }}"
    
    - name: Save Build.Definition Bundles
      uses: actions/upload-artifact@v2
      with:
        name: VSExt-Build.Definition.${{ matrix.config.name }}
        path: .\Emscripten.Build.Definition\bin\${{ matrix.config.config-name }}\*.vsix  
        
    - name: Save Bundles
      uses: actions/upload-artifact@v2
      with:
        name: VSExt-Emscripten.Debugger.${{ matrix.config.name }}
        path: .\Emscripten.Debugger\bin\${{ matrix.config.name }}\*.vsix  
 
  deploy:

    if: ${{ contains(github.ref, 'tags/v') }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Restore Bundles
        uses: actions/download-artifact@v2
        with:
          name: VSExt-Build.Definition.vs2017
          path: .

      - name: Rename VSExt-Build.Definitio for vs2017
        run: |
          cp Emscripten.Build.Definition.vsix Emscripten.Build.Definition.vs2017.vsix

      - name: Restore Bundles
        uses: actions/download-artifact@v2
        with:
          name: VSExt-Build.Definition.vs2022
          path: .

      - name: Restore Bundles
        uses: actions/download-artifact@v2
        with:
          name: VSExt-Emscripten.Debugger.vs2022
          path: .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload Release Asset
        id: upload-build-support-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Emscripten.Build.Definition.vsix
          asset_name: Emscripten.Build.Definition.vsix
          asset_content_type: application/vsix

      - name: Upload Release Asset (vs2017)
        id: upload-build-support-package-for-vs2017
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Emscripten.Build.Definition.vs2017.vsix
          asset_name: Emscripten.Build.Definition.vs2017.vsix
          asset_content_type: application/vsix

      - name: Upload Release Asset
        id: upload-debugger-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Emscripten.Debugger.vsix
          asset_name: Emscripten.Debugger.vsix
          asset_content_type: application/vsix
